import { IsString, IsOptional, IsUUID, IsDateString } from 'class-validator';

export class CreateWargaDto {
  // id generated by DB, so we usually don't accept it from client
  @IsString()
  nama: string;

  @IsOptional()
  @IsString()
  tempat_lahir?: string;

  @IsOptional()
  @IsDateString()
  tanggal_lahir?: string; // ISO string, will be converted to Date by ORM

  @IsOptional()
  @IsString()
  no_telp?: string;

  @IsOptional()
  @IsString()
  jenis_kelamin?: string;

  @IsOptional()
  @IsString()
  agama?: string;

  @IsOptional()
  @IsString()
  golongan_darah?: string;

  @IsOptional()
  @IsString()
  pendidikan_terakhir?: string;

  @IsOptional()
  @IsString()
  pekerjaan?: string;

  @IsOptional()
  @IsString()
  peran?: string;

  @IsOptional()
  @IsString()
  status?: string;

  // di DB default gen_random_uuid(), tapi biasanya ini FK ke data_keluarga,
  // jadi dari sisi API kita terima saja
  @IsOptional()
  @IsUUID()
  keluarga_id?: string;

  // created_at diisi otomatis, jadi tidak perlu di DTO
}
