import { IsString, IsOptional, IsUUID, IsDateString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class CreateWargaDto {
  // id generated by DB, so we usually don't accept it from client
  @ApiProperty({ example: 'Budi Santoso', description: 'Nama lengkap warga', })
  @IsString()
  nama: string;

  @ApiProperty({ example: 'Jakarta', required: false, description: 'Tempat lahir warga' })
  @IsOptional()
  @IsString()
  tempat_lahir?: string;

  @ApiProperty({ example: '2000-01-15', required: false, description: 'Tanggal lahir (ISO date string YYYY-MM-DD)' })
  @IsOptional()
  @IsDateString()
  tanggal_lahir?: string; // ISO string, will be converted to Date by ORM

  @ApiProperty({ example: '081234567890', required: false, description: 'Nomor telepon' })
  @IsOptional()
  @IsString()
  no_telp?: string;

  @ApiProperty({ example: 'laki-laki', required: false, description: 'Jenis kelamin' })
  @IsOptional()
  @IsString()
  jenis_kelamin?: string;

  @ApiProperty({ example: 'Islam', required: false, description: 'Agama' })
  @IsOptional()
  @IsString()
  agama?: string;

  @ApiProperty({ example: 'O', required: false, description: 'Golongan darah' })
  @IsOptional()
  @IsString()
  golongan_darah?: string;

  @ApiProperty({ example: 'S1', required: false, description: 'Pendidikan terakhir' })
  @IsOptional()
  @IsString()
  pendidikan_terakhir?: string;

  @ApiProperty({ example: 'Karyawan Swasta', required: false, description: 'Pekerjaan' })
  @IsOptional()
  @IsString()
  pekerjaan?: string;

  @ApiProperty({ example: 'Ketua RT', required: false, description: 'Peran di lingkungan' })
  @IsOptional()
  @IsString()
  peran?: string;

  @ApiProperty({ example: 'Aktif', required: false, description: 'Status keaktifan warga' })
  @IsOptional()
  @IsString()
  status?: string;

  // di DB default gen_random_uuid(), tapi biasanya ini FK ke data_keluarga,
  // jadi dari sisi API kita terima saja
  @ApiProperty({ example: 'd3b07384-d9a0-4a2f-bf7e-123456789abc', required: false, description: 'ID keluarga (FK ke data_keluarga)', })
  @IsOptional()
  @IsUUID()
  keluarga_id?: string;

  // created_at diisi otomatis, jadi tidak perlu di DTO
}
